---
title: "class_5_3_2020: sampling"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(fs)
library(googlesheets4)
library(janitor)
library(moderndive)
library(gt)

```

```{r, include=FALSE}

sheets_deauth()
x <- read_sheet(ss = "14HmwN2cEVAJHupuehCuLdwG9BXtR3COrxDgaaylLhkA") %>% 
  clean_names()

x %>% arrange(desc(red))

```

```{r, echo=FALSE}
x %>% ggplot(aes(red)) + geom_bar()
```

```{r}

y <- x %>% mutate(perc_red = red / (red +white))

y %>% ggplot(aes(perc_red)) +
  geom_histogram(bins = 20)
```

```{r}
large_sample <- tibble(bogs = 1:10000, color = c(rep("red", 2000), rep("white", 8000)))

simulate <- function(large_sample) {
  large_sample %>% 
  rep_sample_n(size = 25, reps = 51) %>% 
  summarize(red_sum = sum(color == "red")) %>% 
  mutate(percent_red = red_sum / 25)
}
  

sim_results <- tibble(sim_ID = 1:3, 
                      results = map(simulate()))




ten_times <- tibble(results = map(1:n ~ simulate(n)))


ten_times

ggplot(ab, aes(percent_red)) + geom_histogram(bins = 20)

```
